AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graphql
  SAM Template for the serverless cms - api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID: 'test-access-key-id'
        AWS_SECRET_ACCESS_KEY: 'test-secret-access-key'
        AWS_REGION: 'localhost'
        AWS_SSL_ENABLED: false
        AWS_DYNAMODB_API_VERSION: '2012-08-10'
        AWS_DYNAMODB_ENDPOINT: 'http://192.168.86.82:8000'
        AWS_S3_VERSION: '2006-03-01'
        AWS_S3_ENDPOINT: 'http://192.168.86.82:9000'
        AWS_S3_BUCKET: 'serverless-cms.files.dev'

Resources:
  publicGraphql:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/publicGraphql/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        graphql:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /graphql
            Method: post
            Auth:
              Authorizer: 'NONE'
  publicImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resources/publicImages/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        imageProcess:
          Type: Api
          Properties:
            Path: /image-process
            Method: get
            Auth:
              Authorizer: 'NONE'

Outputs:
  # TODO: need to update the following for production release
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GraphQLApi:
    Description: 'API Gateway endpoint URL for Prod stage for GraphQL function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/'
  GraphQLFunction:
    Description: 'GraphQL Lambda Function ARN'
    Value: !GetAtt GraphQLFunction.Arn
  GraphQLFunctionIamRole:
    Description: 'Implicit IAM Role created for GraphQL function'
    Value: !GetAtt GraphQLFunctionRole.Arn
