AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graphql

  Sample SAM Template for graphql

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  publicGraphql:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/publicGraphql/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        graphql:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /graphql
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GraphQLApi:
    Description: 'API Gateway endpoint URL for Prod stage for GraphQL function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/'
  GraphQLFunction:
    Description: 'GraphQL Lambda Function ARN'
    Value: !GetAtt GraphQLFunction.Arn
  GraphQLFunctionIamRole:
    Description: 'Implicit IAM Role created for GraphQL function'
    Value: !GetAtt GraphQLFunctionRole.Arn
