version: '3.7'
services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - 8000:8000
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb']
